# Vectorisation and Gradient Descent
- COMP 1801 IT lab: 09 Oct 2020
$\newcommand{\Vec}[1]{\boldsymbol{#1}}$
$\newcommand{\Mat}[1]{\boldsymbol{#1}}$
## Aim
- Learn the ability vectorisation notation and the ability to convert equations to a modern language code such as Numpy
- Learn how effective vectorisation is.
- Learn how gradient descent works 
## Note to execute a cell, press SHIFT + ENTER

## Notation
- $\mathbb{R}$: the set of real numbers
- $\mathbb{R}^{m \times n}$: the set of matrices of size $m \times n$
- $\mathbb{R}^{m}$: the set of $m$ dimensional real vectors, or matrices of $m \times n$ &emsp; ($\mathbb{R}^{m} = \mathbb{R}^{m \times 1}$)
- Bold upper case (e.g. $\Mat{A}$): a matrix
$$
\Mat{A} 
= \begin{bmatrix}
a_{0,0} & a_{0,1} & \cdots & a_{0,n-1} \\
a_{1,0} & a_{1,1} & \cdots & a_{1,n-1} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m-1,0} & a_{m-1,1} & \cdots & a_{m-1,n-1} \\
\end{bmatrix}
\in \mathbb{R}^{m \times n}
$$
- Bold lower case (e.g. $\Vec{v}$): a vector (a matrix whose column size is one)
$$
\Vec{v} 
= \begin{bmatrix}
v_{0,0} \\
v_{1,0} \\
\vdots \\
v_{m-1,0} \\
\end{bmatrix}
\in \mathbb{R}^{m \times 1}
$$


## Import libraries. Do not forget!

In [1]:
# Import NumPy, which can deal with multi-dimensional arrays such as matrix intuitively.
import numpy as np

# For elapsed time measurement.
import time


## Element notation
- $[\Mat{A}]_{i,j}$ denotes the element in the $i$-th row and $j$-th column of the matrix $\Mat{A}$.
- $\mathtt{A[i,j]}$ is the element in the $i$-th row and $j$-th column of the Numpy 2d-array $\mathtt{A}$.
- $[\Mat{A}]_{i,*}$ denotes the $i$-th row of the matrix $\Mat{A}$.
- $\mathtt{A[i,:]}$ is the Numpy 1d-array given by the $i$-th row of the Numpy 2d-array $\mathtt{A}$.
- $[\Mat{A}]_{*,j}$ denotes the $j$-th column of the matrix $\Mat{A}$.
- $\mathtt{A[:,j]}$ is the Numpy 1d-array given by the $j$-th column of the Numpy 2d-array $\mathtt{A}$.
- $[\Mat{v}]_{i}$ denotes the $i$-th element of the vector $\Vec{v}$, or the element in the $i$-th row and $0$-th column of the "matrix" $\Vec{v}$.



In [2]:
A = np.arange(12).reshape([3, 4])
print('A=')
print(A)
print('A[1,3]=')
print(A[1,3])
print('A[2,1]=')
print(A[2,1])
print('A[1, :]=')
print(A[1, :])
print('A[2, :]=')
print(A[2, :])
print('A[:, 0]=')
print(A[:, 0])
print('A[:, 2]=')
print(A[:, 2])
print('A[:, :]=')
print(A[:, :])


A=
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
A[1,3]=
7
A[2,1]=
9
A[1, :]=
[4 5 6 7]
A[2, :]=
[ 8  9 10 11]
A[:, 0]=
[0 4 8]
A[:, 2]=
[ 2  6 10]
A[:, :]=
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## Element-wise comparison
- $
[\Mat{A}=\Mat{B}]_{i,j} :=
\begin{cases} 
\mathrm{True}, & \textrm{if $[\Mat{A}]_{i,j} = [\Mat{B}]_{i,j}$} \\
\mathrm{False}, & \textrm{if $[\Mat{A}]_{i,j} \ne [\Mat{B}]_{i,j}$} \\
\end{cases}
$

- $
\mathtt{(A==B)[i,j]} :=
\begin{cases} 
\mathrm{True}, & \textrm{if $\mathtt{A[i,j]} = \mathtt{B[i,j]}$} \\
\mathrm{False}, & \textrm{if $\mathtt{A[i,j]} \ne \mathtt{B[i,j]}$} \\
\end{cases}
$

In [3]:
O = np.zeros([4, 4]) # 4 x 4 zero matrix
I = np.eye(4, 4) # 4 x 4 identity matrix
print('O =')
print(O)
print('I =')
print(I)
print('(O==I) =')
print(O==I)

O =
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
I =
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(O==I) =
[[False  True  True  True]
 [ True False  True  True]
 [ True  True False  True]
 [ True  True  True False]]


## Applying scalar function to matrix
Let $\Mat{A} \in \mathbb{R}^{m \times n}$, and $f: \mathbb{R} \to \mathbb{R}$.
- $[f(\Mat{A})]_{i, j} := f([\Mat{A}]_{i, j})$, for $i = 0, 1, \dots, m-1$, $j = 0, 1, \dots, n-1$.
- $\mathtt{f(A)[i, j]} := \mathtt{f(A[i, j])}$, for $\mathtt{i} = \mathtt{0, 1, \dots, m-1}$, $\mathtt{j} = \mathtt{0, 1, \dots, n-1}$.

Let $\Mat{A}, \Mat{B} \in \mathbb{R}^{m \times n}$, and $g: \mathbb{R} \times \mathbb{R} \to \mathbb{R}$.
- $[g(\Mat{A}, \Mat{B})]_{i, j} := g([\Mat{A}]_{i, j}, [\Mat{B}]_{i, j})$, for $i = 0, 1, \dots, m-1$, $j = 0, 1, \dots, n-1$.
- $\mathtt{g(A, B)[i, j]} := \mathtt{g(A[i, j], B[i, j])}$, for $\mathtt{i} = \mathtt{0, 1, \dots, m-1}$, $\mathtt{j} = \mathtt{0, 1, \dots, n-1}$.

In particular, for $i = 0, 1, \dots, m-1$, $j = 0, 1, \dots, n-1$.
- $[\Mat{A} + \Mat{B}]_{i, j} := [\Mat{A}]_{i, j} + [\Mat{B}]_{i, j}$
- $\mathtt{(A + B)[i, j]} := \mathtt{A[i, j] + B[i, j]}$
- $[\Mat{A} - \Mat{B}]_{i, j} := [\Mat{A}]_{i, j} - [\Mat{B}]_{i, j}$
- $\mathtt{(A - B)[i, j]} := \mathtt{A[i, j] - B[i, j]}$
- $[\Mat{A} \otimes \Mat{B}]_{i, j} := [\Mat{A}]_{i, j} [\Mat{B}]_{i, j}$
- $\mathtt{(A * B)[i, j]} := \mathtt{A[i, j] * B[i, j]}$
- $[\Mat{A} \oslash \Mat{B}]_{i, j} := [\Mat{A}]_{i, j} / [\Mat{B}]_{i, j}$
- $\mathtt{(A / B)[i, j]} := \mathtt{A[i, j] / B[i, j]}$

Note: $\otimes$ and $\oslash$ denote elementwise multiplication and division, respectively.

In [4]:
def f(x):
  return np.sin(x)
m = 3
n = 5
A = np.random.normal(size=[m, n]) # m x n random matrix
f_A_for = np.zeros([3, 5])
for i in range(m):
  for j in range(n):
    f_A_for[i, j] = f(A[i, j])
print('A =')
print(A)
print('f(A) =')
print(f(A))
print('f(A) computed elementwisely')
print(f_A_for)

A =
[[ 3.29820962 -0.13911757  0.02806456 -0.08045294 -1.86337893]
 [ 0.03277366  0.85766287  0.93486734  0.00474801  1.34425803]
 [ 0.44096288  1.1310595   0.58176423  0.66834353  0.82292006]]
f(A) =
[[-0.15597748 -0.13866926  0.02806087 -0.08036617 -0.95750218]
 [ 0.03276779  0.75631566  0.8045203   0.00474799  0.97444975]
 [ 0.42681043  0.90486373  0.54949879  0.61968676  0.73313484]]
f(A) computed elementwisely
[[-0.15597748 -0.13866926  0.02806087 -0.08036617 -0.95750218]
 [ 0.03276779  0.75631566  0.8045203   0.00474799  0.97444975]
 [ 0.42681043  0.90486373  0.54949879  0.61968676  0.73313484]]


## Basic operation for a matrix
Let $c \in \mathbb{R}, \Mat{A} \in \mathbb{R}^{m \times n}$. $\mathtt{A.shape = (m, n)}$
- Scalar product $c \Mat{A}$ is given by $[c \Mat{A}]_{i,j} := c[\Mat{A}]_{i,j}$, for $i = 0, 1, \dots, m-1$, $j = 0, 1, \dots, n-1$.
- Scalar product $\mathtt{c * A}$ is given by $\mathtt{(c * A) [i, j]} := \mathtt{c * A [i, j]}$, for $\mathtt{i} = \mathtt{0, 1, \dots, m-1}$, $\mathtt{j} = \mathtt{0, 1, \dots, n-1}$.
- The transpose $\Mat{A}^{\top} \in \mathbb{R}^{n \times m}$ is given by $[\Mat{A}^{\top}]_{j,i} := [\Mat{A}]_{i,j}$, for $i = 0, 1, \dots, m-1$, $j = 0, 1, \dots, n-1$.
- The transpose $\mathtt{A.T}$, where $\mathtt{A.T.shape = (n, m)}$ is given by $\mathtt{(A.T) [j, i]} := \mathtt{A [i, j]}$, for $\mathtt{i} = \mathtt{0, 1, \dots, m-1}$, $\mathtt{j} = \mathtt{0, 1, \dots, n-1}$.


## Broadcasting
Let 
- $\Mat{A, B} \in \mathbb{R}^{m \times n}$, $\Vec{u} \in \mathbb{R}^{m \times 1}$, $\Vec{v} \in \mathbb{R}^{n \times 1}$, and $c \in \mathbb{R}^{1 \times 1}$,
- $\mathtt{A.shape} = \mathtt{(m, n)}$, $\mathtt{B.shape} = \mathtt{(m, n)}$, $\mathtt{u.shape} = \mathtt{(m, 1)}$, $\mathtt{v.shape} = \mathtt{(n, 1)}$, $\mathtt{c.shape} = \mathtt{(1, 1)}$,
- $f: \mathbb{R}^{m \times n} \times \mathbb{R}^{m \times n} \to \mathbb{R}^{1 \times 1}, \mathbb{R}^{m \times 1}, \mathbb{R}^{1 \times n}, \textrm{ or } \mathbb{R}^{m \times n}$, 
- $\mathtt{f(A,B).shape} = \mathtt{(1, 1)}$, $\mathtt{(m, 1)}$, $\mathtt{(1, n)}$, or $\mathtt{(m, n)}$.

Then
- $f(\Mat{A}, \Vec{u}^\top) := f(\Mat{A}, \Vec{u}^\top \Vec{1}_{n \times 1})$,
- $\mathtt{f(A, u.T)} := \mathtt{f(A, u.T\ @\ np.ones([n, 1]))}$,
- $f(\Mat{A}, \Vec{v}) := f(\Mat{A}, \Vec{1}_{m \times 1}^\top \Vec{v})$,
- $\mathtt{f(A, v)} := \mathtt{f(A, np.ones([m, 1]).T\ @\ v)}$,
- $f(\Mat{A}, c) := f(\Mat{A}, \Vec{1}_{m \times 1}^\top c \Vec{1}_{n \times 1})$,
- $\mathtt{f(A, c)} := \mathtt{f(A, np.ones([m, 1]).T\ @\ c\ @ \ np.ones([1, n]))}$,
- $f(\Vec{u}^\top, \Mat{B}) := f(\Vec{u}^\top \Vec{1}_{n \times 1}, \Mat{B})$,
- $\mathtt{f(u.T, B)} := \mathtt{f(u.T\ @\ np.ones([n, 1]), B)}$,
- $f(\Vec{v}, \Mat{B}) := f(\Vec{1}_{m \times 1}^\top \Vec{v}, \Mat{B})$,
- $\mathtt{f(v, B)} := \mathtt{f(np.ones([m, 1]).T\ @\ v, B)}$,
- $f(c, \Mat{B}) := f(\Vec{1}_{m \times 1}^\top c \Vec{1}_{n \times 1}, \Mat{B})$,
- $\mathtt{f(c, B)} := \mathtt{f(np.ones([m, 1]).T\ @\ c\ @ \ np.ones([1, n]), B)}$,
- $f(\Vec{u}^\top, \Vec{v}) := f(\Vec{u} \Vec{1}_{1 \times n}, \Vec{1}_{m \times 1}^\top \Vec{v})$,
- $\mathtt{f(u.T, v)} := \mathtt{f(u.T\ @\ np.ones([n, 1]), np.ones([n, 1])\ @\ v)}$,
- $f(\Vec{v}, \Vec{u}^\top) := f(\Vec{1}_{m \times 1}^\top \Vec{v}, \Vec{u} \Vec{1}_{1 \times n})$,
- $\mathtt{f(v, u.T)} := \mathtt{f(np.ones([n, 1])\ @\ v, u.T\ @\ np.ones([n, 1]))}$,

In particular, $f$ can be $\mathtt{+, -, *, /}$
- $\Mat{A} + \Vec{u}^\top := \Mat{A} + \Vec{u}^\top \Vec{1}_{n \times 1}$,
- $\mathtt{A + u.T} := \mathtt{A + u.T\ @\ np.ones([n, 1])}$,
- etc.

In [5]:
u = np.array([[0], [1], [2]])
v = np.array([[3], [7]])
print('u.T =')
print(u.T)
print('v =')
print(v)
print('u.T * v =')
print(u.T * v)

u.T =
[[0 1 2]]
v =
[[3]
 [7]]
u.T * v =
[[ 0  3  6]
 [ 0  7 14]]


## Matrix product (dot product)
Let $\Mat{A} \in \mathbb{R}^{m \times l}, \Mat{B} \in \mathbb{R}^{l \times n}$, or $\mathtt{A.shape} = \mathtt{(m, l)}$, $\mathtt{B.shape} = \mathtt{(l, n)}$
- $[\Mat{A} \Mat{B}]_{i, j} := \sum_{k=0}^{l-1} [\Mat{A}]_{i, k} [\Mat{B}]_{k, j}$, for $i = 0, 1, \dots, m-1$, $j = 0, 1, \dots, n-1$.
- $\mathtt{(A @ B)[i, j]} := \mathtt{np.sum(A[i, :] * B[:, j])}$, for $\mathtt{i} = \mathtt{0, 1, \dots, m-1}$, $\mathtt{j} = \mathtt{0, 1, \dots, n-1}$.


In [6]:
m = 3
n = 5
l = 4
A = np.random.normal(size=[m, l]) # m x l random matrix
B = np.random.normal(size=[l, n]) # l x n random matrix
AB_at = A @ B
AB_for_for_sum = np.zeros([m, n])
for i in range(m):
  for j in range(n):
    AB_for_for_sum[i, j] = np.sum(A[i, :] * B[:, j])
AB_for_for_for = np.zeros([3, 5])
for i in range(m):
  for j in range(n):
    for k in range(l):
      AB_for_for_for[i, j] += np.sum(A[i, k] * B[k, j])
print('A =')
print(A)
print('B =')
print(B)
print('A @ B =')
print(AB_at)
print('AB computed by the for for sum strategy =')
print(AB_for_for_sum)
print('AB computed by the for for for strategy =')
print(AB_for_for_for)

A =
[[ 0.84984235  2.3562961   1.21184383 -1.15406302]
 [-0.45041103 -0.10135864  0.30202544 -0.66442109]
 [-0.16571271 -0.38960072  2.07519267  0.776192  ]]
B =
[[ 0.37391897 -1.5020347  -0.48967232 -2.18566859 -0.42205756]
 [ 0.99895176 -0.63280997  0.62397891 -0.55025812 -0.21312366]
 [ 1.28816385 -2.70644209 -0.27749339  0.062265    0.1594035 ]
 [-0.28977743 -0.9469976   0.96093925 -2.77336667 -0.26781403]]
A @ B =
[[ 4.56707314 -4.95447062 -0.39112831  0.12205057 -0.35861841]
 [ 0.31192288  0.55246457 -0.56497021  2.9017116   0.43778651]
 [ 1.99710982 -5.8559913   0.00806341 -1.4468791   0.27589131]]
AB computed by the for for sum strategy =
[[ 4.56707314 -4.95447062 -0.39112831  0.12205057 -0.35861841]
 [ 0.31192288  0.55246457 -0.56497021  2.9017116   0.43778651]
 [ 1.99710982 -5.8559913   0.00806341 -1.4468791   0.27589131]]
AB computed by the for for for strategy =
[[ 4.56707314 -4.95447062 -0.39112831  0.12205057 -0.35861841]
 [ 0.31192288  0.55246457 -0.56497021  2.9017116  

## Efficiency of vectorisation

In [7]:
m = 30
n = 50
l = 40
A = np.random.normal(size=[m, l]) # m x l random matrix
B = np.random.normal(size=[l, n]) # l x n random matrix

start_time_AB_at = time.time()
AB_at = A @ B
end_time_AB_at = time.time()
elapsed_time_AB_at = end_time_AB_at - start_time_AB_at
print('Elapsed time for A @ B =')
print(elapsed_time_AB_at)

start_time_AB_for_for_for = time.time()
AB_for_for_for = np.zeros([m, n])
for i in range(m):
  for j in range(n):
    for k in range(l):
      AB_for_for_for[i, j] += np.sum(A[i, k] * B[k, j])
end_time_AB_for_for_for = time.time()
elapsed_time_AB_for_for_for = end_time_AB_for_for_for - start_time_AB_for_for_for

print('Elapsed time for the for for for strategy =')
print(elapsed_time_AB_for_for_for)

Elapsed time for A @ B =
9.72747802734375e-05
Elapsed time for the for for for strategy =
0.30290699005126953


## Load data

In [8]:
from sklearn.datasets import load_boston, load_breast_cancer, fetch_california_housing
dataset = fetch_california_housing()
# print(dataset.DESCR)
# print(dataset.feature_names)
raw_X = dataset.data # get feature data
m, n = raw_X.shape
y = dataset.target # get target data as a size-m 1-d array
Y = y[:, np.newaxis] # convert the target data to a m x 1 2-d array
print('number of examples m =', m)
print('number of columns n =', n)


number of examples m = 20640
number of columns n = 8


In [9]:
def standardise(raw_X):
  mu = np.mean(raw_X, axis=0, keepdims=True)
  sigma = np.std(raw_X, axis=0, keepdims=True)
  X_standardised = np.zeros_like(raw_X)

  # Modify the code - correct definition of X_standardised: start

  # X_standardised = 

  # Modify the code: end

  X_standardised = (raw_X - mu) / sigma  # Broadcasting is used here
  return X_standardised 


## Standardisation (YOU NEED TO MODIFY CODE)

### Mean
- $\mathtt{np.mean(A, axis=0, keepdims=True).shape} = \mathtt{(1, n)}$
- $\mathtt{np.mean(A, axis=0, keepdims=True)[0, j]}$ is the mean of all the elements in the $\mathtt{j}$-th column of matrix $\mathtt{A}$.
- $\mathtt{np.mean(A, axis=1, keepdims=True).shape} = \mathtt{(m, 1)}$
- $\mathtt{np.mean(A, axis=1, keepdims=True)[i, 0]}$ is the mean of all the elements in the $\mathtt{i}$-th row of matrix $\mathtt{A}$.

### Standard deviation
- $\mathtt{np.std(A, axis=0, keepdims=True).shape} = \mathtt{(1, n)}$
- $\mathtt{np.std(A, axis=0, keepdims=True)[0, j]}$ is the standard deviation of all the elements in the $\mathtt{j}$-th column of matrix $\mathtt{A}$.
- $\mathtt{np.std(A, axis=1, keepdims=True).shape} = \mathtt{(m, 1)}$
- $\mathtt{np.std(A, axis=1, keepdims=True)[i, 0]}$ is the standard deviation of all the elements in the $\mathtt{i}$-th row of matrix $\mathtt{A}$.

Let's implement the standardisation in the following cell! For the $j$-th column vector $\tilde{\Vec{x}}_{j}$, the standardised vector $\tilde{\Vec{x}}_{j}^\mathrm{standardised}$ is given by 
$$ \tilde{\Vec{x}}^\mathrm{standardised}_{j} := (\tilde{\Vec{x}}_{j} - \Vec{1}_{m} \mu_{j}) \oslash (\Vec{1}_{m} \sigma_{j}),$$
where $\mu_{j}$ is the mean of $\tilde{\Vec{x}}_{j}$, and $\sigma_{j}$ is the standard deviation of $\tilde{\Vec{x}}_{j}$.



## Appending one vector to the feature matrix. (corresponding to $\theta_{0}$)

In [10]:
def append_one_to(X_without_one):
  X_with_one = np.pad(X_without_one, ((0, 0), (1, 0)), constant_values=1)
  return X_with_one


## Now, preprocess our feature data matrix!

In [11]:
X = append_one_to(standardise(raw_X))

## Mean squared error (YOU NEED TO MODIFY CODES)
$$J(\Vec{\theta}; \Mat{X}, \Vec{y}) = \frac{1}{2} \times \frac{1}{m} \sum_{i=0}^{m-1} ([\Mat{X}]_{i, *} \Vec{\theta} - [\Vec{y}]_{i})^2 = \frac{1}{2 m}(\Mat{X} \Vec{\theta} - \Vec{y})^\top (\Mat{X} \Vec{\theta} - \Vec{y})$$

Let's implement the mean squared error in the following cell!
- Advanced: Do you have a way to implement it without using $m$ or $n$?

In [12]:
def mean_squared_error(Theta, X, Y):
  m, n = X.shape

  mse_matrix = 100000000000 * np.ones([1, 1]) # result of the mse should be 1 x 1 matrix

  # Modify the code - correct definition of mse_matrix: start

  
  #mse_matrix =  ((1/2) * (1/m)) * ((X @ Theta - Y). T @ (X @ Theta - Y))
  mse_matrix = (1/(2*m)) * ((X @ Theta - Y).T @ (X @ Theta - Y))
  

  # Modify the code: end

  mse_scalar = np.squeeze(mse_matrix) # convert a 1 x 1 matrix to scalar 
  return mse_scalar


## Let's calculate the loss function! 

In [13]:
def calc_mse(Theta, X, Y):
  print('Current parameter Theta')
  print(Theta)
  mse = mean_squared_error(Theta, X, Y)
  print('Cost function MSE')
  print(mse)
  return mse

Theta = 0.1 * np.ones([9, 1])
calc_mse(Theta, X, Y)
print('Hopefully, you get around', 2.5618)
Theta = 0.2 * np.ones([9, 1])
calc_mse(Theta, X, Y)
print('Hopefully, you get around', 2.3977)


Current parameter Theta
[[0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]]
Cost function MSE
2.561821183325288
Hopefully, you get around 2.5618
Current parameter Theta
[[0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.2]]
Cost function MSE
2.3976898863719383
Hopefully, you get around 2.3977


## Gradient computation (YOU NEED TO MODIFY CODES)
In linear regression, the gradient is given by
$$ \frac{\partial}{\partial \Vec{\theta}} J (\Vec{\theta}) = \frac{1}{m} (\Mat{X}^\top \Mat{X} \Vec{\theta} - \Mat{X}^\top \Vec{y})$$

In [14]:
def get_gradient(Theta, X, Y):
  m, n = X.shape
  gradient_of_Theta = np.zeros_like(Theta)

  # Modify the code - correct definition of gradient_of_Theta: start
  # gradient_of_Theta = (1/m) * (X.T @ X @ Theta - X.T @ Y)
  gradient_of_Theta = (1/m)* (X. T @ X @ Theta - X. T @ Y )
  
  # Modify the code: end

  return gradient_of_Theta


## Update the parameter along the gradient (YOU NEED TO MODIFY CODES)
$$ \Vec{\theta} \gets \Vec{\theta} - \lambda \frac{\partial}{\partial \Vec{\theta}} J (\Vec{\theta}), $$
where $\lambda$ is the learning rate.


In [15]:
def gradient_descent_update(Theta, X, Y, learning_rate):
  Theta_new = np.zeros_like(Theta)
  gradient_of_Theta = get_gradient(Theta, X, Y)

  # Modify the code - correct definition of Theta_new: start

  Theta_new = Theta - learning_rate * gradient_of_Theta

  # Modify the code: end
  return Theta_new


## Let's execute the gradient descent!

In [16]:
def gradient_descent(Theta_initial, X, Y, n_iterations=1000, learning_rate=0.1, n_interval_steps_for_display=100):
  if len(Theta_initial.shape) != 2:
    raise ValueError('Theta_initial must be 2d-array.')
  if Theta_initial.shape[1] != 1:
    raise ValueError('The number of columns in Theta_initial must be 1.')
  if X.shape[1] != Theta_initial.shape[0]:
    raise ValueError('The number of columns in X and the number of rows in Theta_initial must be the same. X.shape =', X.shape, 'Theta_initial.shape =', Theta_initial.shape)
  Theta = Theta_initial  
  calc_mse(Theta, X, Y)
  for i_iteration in range(n_iterations):
    Theta = gradient_descent_update(Theta, X, Y, learning_rate)
    if (i_iteration + 1) % n_interval_steps_for_display == 0:
      print(i_iteration + 1, '-th iteration.')
      calc_mse(Theta, X, Y)
  final_mse = calc_mse(Theta, X, Y)
  return Theta, final_mse

Theta_initial = np.zeros([X.shape[1], 1])
n_iterations = 1000
learning_rate = 0.1
Theta, final_mse = gradient_descent(Theta_initial, X, Y, n_iterations=n_iterations, learning_rate=learning_rate)
print('Hopefully, you get around', 0.2621)


Current parameter Theta
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Cost function MSE
2.8052415994936264
100 -th iteration.
Current parameter Theta
[[ 2.06850323]
 [ 0.81682107]
 [ 0.17679998]
 [-0.12801589]
 [ 0.14202428]
 [ 0.01663505]
 [-0.04392645]
 [-0.48692142]
 [-0.45059052]]
Cost function MSE
0.2764460864036497
200 -th iteration.
Current parameter Theta
[[ 2.06855817]
 [ 0.83914273]
 [ 0.14724148]
 [-0.23357274]
 [ 0.25730724]
 [ 0.00573741]
 [-0.04193931]
 [-0.6832587 ]
 [-0.65260618]]
Cost function MSE
0.26543131496920164
300 -th iteration.
Current parameter Theta
[[ 2.06855817e+00]
 [ 8.43400811e-01]
 [ 1.33081686e-01]
 [-2.69595327e-01]
 [ 2.99398803e-01]
 [ 5.31172189e-04]
 [-4.08323317e-02]
 [-7.82482676e-01]
 [-7.53679217e-01]]
Cost function MSE
0.2629947469822588
400 -th iteration.
Current parameter Theta
[[ 2.06855817e+00]
 [ 8.41762271e-01]
 [ 1.26190525e-01]
 [-2.78813979e-01]
 [ 3.12437411e-01]
 [-1.95446495e-03]
 [-4.02144530e-02]
 [-8.34255784e-01]
 [-8

In [ ]:
# --- Edit the following information ---
your_email_address = 'ab0000x@gre.ac.uk'
your_student_id = '000000000'
your_first_name = 'your_first_name'
your_last_name = 'your_last_name'
# --- Edit the above information ---

# After filling the above information, execute this cell by pressing Shift + Enter

# --- Don't touch the below ---
# Execute after filling the above descriptions by pressing Shift + Enter
!pip install pycryptodome
import urllib.request
from bs4 import BeautifulSoup
import requests, warnings
import json
from Crypto.PublicKey import RSA
from Crypto.Cipher import PKCS1_OAEP

submission_id = 'comp-1801_20201009-01'
student_information = dict(email=your_email_address, id=your_student_id, first_name=your_first_name, last_name=your_last_name)
answer = dict(Theta=Theta.tolist(), final_mse=final_mse.tolist())
submission_dict = dict(submission_id=submission_id, student_information=student_information, answer=answer)
submission_json = json.dumps(submission_dict)

def get_questions(in_url):
    res = urllib.request.urlopen(in_url)
    soup = BeautifulSoup(res.read(), 'html.parser')
    get_names = lambda f: [v for k,v in f.attrs.items() if 'label' in k]
    get_name = lambda f: get_names(f)[0] if len(get_names(f))>0 else 'unknown'
    all_questions = soup.form.findChildren(attrs={'name': lambda x: x and x.startswith('entry.')})
    return {get_name(q): q['name'] for q in all_questions}

def submit_response(form_url, cur_questions, verbose=False, **answers):
    submit_url = form_url.replace('/viewform', '/formResponse')
    form_data = {'draftResponse':[],
                'pageHistory':0}
    for v in cur_questions.values():
        form_data[v] = ''
    for k, v in answers.items():
        if k in cur_questions:
            form_data[cur_questions[k]] = v
        else:
            warnings.warn('Unknown Question: {}'.format(k), RuntimeWarning)
    if verbose:
        print(form_data)
    user_agent = {'Referer':form_url,
                  'User-Agent': "Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.52 Safari/537.36"}
    return requests.post(submit_url, data=form_data, headers=user_agent)


FORM_URL = "https://docs.google.com/forms/d/e/1FAIpQLScNs3Cf6DnNCBCUyPGfp22mI3FYVBfTNbGi0TxZ0_SKo9fgCw/viewform"
anno_questions = get_questions(FORM_URL)
public_key_utf = '''-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp/lFj1VO6DQ+Ot27oamm
KImRJiXz7IlhdlfkAmytONDQAtvgp9/AqfHyIA0+YnaTDGditMK4t1u6s2YvYlW8
5tKbAkbziDAOyaxkepwEw47ldco3hh8p+N42nymWZJp7GKwaHUJ/k1S5sTzFso9o
8/szKGlHUq3lpQdQeWScAirCvCewqJFrJWiLymoS0IbeeCzxCJxqmLwx4kXjCTeU
c9yUqCi+dZ41Cebd8z5y4Ekf58JP+jh/B0VPHV5cR2D/S3zrhWjPnSU4nCKef5pE
b863LlyJ1/sKheanBTq7+9rxMf2rNrsH8Nea4UW2gwtPgOogWFdiWgKYl7B1ks7E
OQIDAQAB
-----END PUBLIC KEY-----'''

split_n = lambda text, n: [ text[i*n:i*n+n] for i in range(len(text)//n) ]
def split_n(string, length):
    return (string[0+i:length+i] for i in range(0, len(string), length))
answer_json_list = split_n(submission_json, 32)
cipher_rsa = PKCS1_OAEP.new(RSA.import_key(public_key_utf.encode('utf-8')))
encrypted_answer_json = '\n'.join([cipher_rsa.encrypt(line.encode()).hex() for line in answer_json_list])
submit_response(FORM_URL, {'answer': 'entry.1985698402'}, **{'answer': encrypted_answer_json})
print('Successfully submitted!!')
print('Check your information: ', ', '.join([': '.join([k, str(v)]) for k, v in student_information.items()]), '\n', 'Your answer: ', ', '.join([': '.join([k, str(v)]) for k, v in answer.items()]))
